services:
  - type: web
    name: safe-link-guard-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: VT_API_KEY
        sync: false  # ستضيفه يدوياً في لوحة تحكم Render
      - key: PYTHON_VERSION
        value: 3.9.0